### ISSUE TITLE
Please help downloading

### ISSUE THREAD

**Issue by Opis335** [xathail/Discord-Auto-Advertiser#11]
Hello can someone please help me download this and use it please we can communicate on discord or where ever thank you so much

**Comment by Shinagami2900** [comment]
Hey if you get help lmk i would like some help too

**Comment by xathail** [comment]
> Hey if you get help lmk i would like some help too
> Hi, what are you stuck with?

**Comment by Opis335** [comment]
im stuck with just downloading it do you think you can jsut make a video on how to download it and run it on a place whee you tun it becuase i also dont know where and also with the requirments aswell thank you so much :)

**Comment by xathail** [comment]
Can't record a video but I can give you steps.
1. Make sure you have python 3.1+ installed. If you don't, you can get this from python.org (and on download, make sure to include pip installation.

2. Go to https://github.com/xathail/Discord-Auto-Advertiser/archive/refs/heads/main.zip and download the repository zip file.

3. Extract the zip file.

4. Open a terminal / command line and navigate into the file. If you're using a graphical operating system, I would recommend navigating into Discord-Auto-Advertiser/Windows UI/

5. Run `pip install -r requirements.txt`

6. Run `python windowsui.py`

Let me know if you need more help!

**Comment by Opis335** [comment]
Acuatly thank you so much i got the gui to work but i cant seem to get the actual bot to start working and also i reccomend you adding a auto dm response and also i think that https://discord.gg/wPwZbTfh might have stolen your service and just adjusted it a little bit but i have no idea

**Comment by xathail** [comment]
> Acuatly thank you so much i got the gui to work but i cant seem to get the actual bot to start working and also i reccomend you adding a auto dm response and also i think that https://discord.gg/wPwZbTfh might have stolen your service and just adjusted it a little bit but i have no idea 

If you've added channels, your message, and your user token, you should be able to press the "Start Advertising" button and it'll start. If that doesn't do anything, check your config.json and make sure nothing is empty in there. If that also doesn't work, please check console to see if there are any errors.

**Comment by Shinagami2900** [comment]
> > Acuatly thank you so much i got the gui to work but i cant seem to get the actual bot to start working and also i reccomend you adding a auto dm response and also i think that https://discord.gg/wPwZbTfh might have stolen your service and just adjusted it a little bit but i have no idea
> 
> If you've added channels, your message, and your user token, you should be able to press the "Start Advertising" button and it'll start. If that doesn't do anything, check your config.json and make sure nothing is empty in there. If that also doesn't work, please check console to see if there are any errors.

tbh idek how to get started or work any of this

**Comment by xathail** [comment]
> > > Acuatly thank you so much i got the gui to work but i cant seem to get the actual bot to start working and also i reccomend you adding a auto dm response and also i think that https://discord.gg/wPwZbTfh might have stolen your service and just adjusted it a little bit but i have no idea
> > 
> > If you've added channels, your message, and your user token, you should be able to press the "Start Advertising" button and it'll start. If that doesn't do anything, check your config.json and make sure nothing is empty in there. If that also doesn't work, please check console to see if there are any errors.
> 
> tbh idek how to get started or work any of this
> 
> Edit: im stuck at the run pip install -r requirements.txt


What can't you understand at this stage / what errors are you getting?

**Comment by Opis335** [comment]
How got stuck at editing the config am I supposed to edit the one inside the gui or the one in the main part and also how do i save it because if i press save it doesnt save when i open it back up

**Comment by xathail** [comment]
> How got stuck at editing the config am I supposed to edit the one inside the gui or the one in the main part and also how do i save it because if i press save it doesnt save when i open it back up 

That's odd. Ok, could you try the other version, so go up to the main folder, run `pip install -r requirements.txt` again, then run `python main.py` and then follow the prompts for it to create your config in the CLI version.

**Comment by Opis335** [comment]
Yesterday when I was trying to run it it hadn’t worked so I asked ChatGPT and he gave me a way to open it but without the setup and I kinda lost that so i do t even know

**Comment by xathail** [comment]
> > How got stuck at editing the config am I supposed to edit the one inside the gui or the one in the main part and also how do i save it because if i press save it doesnt save when i open it back up 
> 
> That's odd. Ok, could you try the other version, so go up to the main folder, run `pip install -r requirements.txt` again, then run `python main.py` and then follow the prompts for it to create your config in the CLI version.

^

**Comment by Opis335** [comment]
how do  iupfate the json files it syas read only i cant get the guided steps to work but lemme try again

**Comment by Opis335** [comment]
ok i accuatly got it to work but when it is sending messages to the channels it sends random pair of numbers diffrent evrytime at the end

**Comment by xathail** [comment]
> ok i accuatly got it to work but when it is sending messages to the channels it sends random pair of numbers diffrent evrytime at the end and auto dm response doesnt seem like its working well
> 

You must've activated message repeat bypass in the config. Open the config.json and set repeatBypass to `n` or anything other than `y`.

**Comment by xathail** [comment]
> ok i accuatly got it to work but when it is sending messages to the channels it sends random pair of numbers diffrent evrytime at the end and auto dm response doesnt seem like its working well
> 

You must've activated message repeat bypass in the config. Open the config.json and set repeatBypass to `n` or anything other than `y`.

**Comment by Opis335** [comment]
> > ok i accuatly got it to work but when it is sending messages to the channels it sends random pair of numbers diffrent evrytime at the end and auto dm response doesnt seem like its working well
> 
> You must've activated message repeat bypass in the config. Open the config.json and set repeatBypass to `n` or anything other than `y`.

Ok its working know but can you check out the dm responder its not working for me

**Comment by xathail** [comment]
> > > ok i accuatly got it to work but when it is sending messages to the channels it sends random pair of numbers diffrent evrytime at the end and auto dm response doesnt seem like its working well
> > 
> > You must've activated message repeat bypass in the config. Open the config.json and set repeatBypass to `n` or anything other than `y`.
> 
> Ok its working know but can you check out the dm responder its not working for me 

Before you start the advertiser, you have to start the auto DM responder. In the CLI, I believe this is option 7, and then option 1.

**Comment by Opis335** [comment]
> > > > ok i accuatly got it to work but when it is sending messages to the channels it sends random pair of numbers diffrent evrytime at the end and auto dm response doesnt seem like its working well
> > > 
> > > 
> > > You must've activated message repeat bypass in the config. Open the config.json and set repeatBypass to `n` or anything other than `y`.
> > 
> > 
> > Ok its working know but can you check out the dm responder its not working for me
> 
> Before you start the advertiser, you have to start the auto DM responder. In the CLI, I believe this is advertising menu option 7, and then advertising menu option 1

i just tried that a few times it still doesnt work for me whenever i send a dm on muliple accounts it doesnt respond do you think you can check it out

**Comment by xathail** [comment]
Download & run resolved, unrelated issues should be created separately.
