### ISSUE TITLE
keeps saying this token is invalid

### ISSUE THREAD

**Issue by nitrox5** [xathail/Discord-Auto-Advertiser#5]
![image](https://github.com/xathail/Discord-Auto-Advertiser/assets/171622159/4b61c2d4-fe98-4441-a4b4-a83289a5219c)
says my token is invalid but it is valid

**Comment by xathail** [comment]
Hi, I'll check if it's working for me when I have free time some point today (BST).

**Comment by nitrox5** [comment]
> Hi, I'll check if it's working for me when I have free time some point today (BST).
> 
> This might come with a few new features.

ok thanks

**Comment by nitrox5** [comment]
> Hi, I'll check if it's working for me when I have free time some point today (BST).
> 
> This might come with a few new features.

any updates

**Comment by xathail** [comment]
Hi, after checking, everything is still working? Are you sure your token was valid? Have you tried manually editing it into the config.json?

**Comment by nitrox5** [comment]
Can it be a bot token or does it have to be human token?
